"""Full-stack launcher: FastAPI API and Taipy GUI as two native servers.

Taipy's frontend requires a live WebSocket (Flask-SocketIO) connection for
state synchronization, which a WSGI-in-ASGI mount cannot proxy correctly
(the upgrade handshake gets rejected). Each server therefore runs with its
own native transport: FastAPI's JSON API under `uvicorn` (ASGI) in an
independent OS subprocess, and the Taipy GUI under its own Flask-SocketIO
development server (which natively speaks WebSocket) in the foreground.

The API is launched via `subprocess.Popen` rather than
`multiprocessing.Process` deliberately: this package exposes a packaged
console-script entry point (`fig-quant`), and `multiprocessing`'s `spawn`
start method (the default on macOS/Windows, and available on Linux) works
by re-importing the entry-point module in the child. Console scripts
generated by build backends call the CLI unconditionally at import time
with no `if __name__ == "__main__":` guard, so a `multiprocessing`-spawned
child does not just run the target function -- it re-executes the whole
`fig-quant serve` command, recursively launching a *second* nested GUI and
API pair that collide on the same ports as the originals. `subprocess.Popen`
starts a genuinely independent process via `execve` and never re-imports
the parent, avoiding that failure mode entirely.
"""

from __future__ import annotations

import subprocess
import sys
import time


def run_full_stack(
    api_host: str = "0.0.0.0",
    api_port: int = 8001,
    gui_host: str = "0.0.0.0",
    gui_port: int = 8000,
) -> None:
    """Starts the FastAPI API (subprocess) and Taipy GUI (foreground).

    Args:
      api_host: Bind host for the FastAPI JSON API.
      api_port: Bind port for the FastAPI JSON API (default 8001, so it
        does not collide with the GUI's default port 8000).
      gui_host: Bind host for the Taipy GUI.
      gui_port: Bind port for the Taipy GUI. This is the port a human
        should point their browser at.

    Raises:
      RuntimeError: If the API subprocess exits before the GUI starts,
        surfacing its stderr instead of leaving a silent port mismatch.
    """
    from fig_quant.web.gui import build_gui

    api_proc = subprocess.Popen(
        [
            sys.executable,
            "-m",
            "uvicorn",
            "fig_quant.web.app:api",
            "--host",
            api_host,
            "--port",
            str(api_port),
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )

    # Give the API a moment to either bind successfully or fail fast, so a
    # bad port/config surfaces immediately instead of as a silent mismatch
    # discovered later by the person in their browser.
    time.sleep(1.0)
    if api_proc.poll() is not None:
        output = api_proc.stdout.read() if api_proc.stdout else ""
        raise RuntimeError(
            f"FastAPI API subprocess exited immediately (code {api_proc.returncode}):\n{output}"
        )

    print(f"FastAPI JSON API:  http://{api_host}:{api_port}  (docs at /docs)")
    print(f"Taipy GUI console: http://{gui_host}:{gui_port}  <-- open this in your browser")

    gui = build_gui()
    try:
        # Taipy's own dev server natively handles the WebSocket upgrade
        # that a WSGI mount cannot; this call blocks until interrupted.
        gui.run(host=gui_host, port=gui_port, use_reloader=False, run_browser=False)
    finally:
        api_proc.terminate()
        try:
            api_proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            api_proc.kill()
